/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formManagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stourestaurant.MyConnect;

/**
 *
 * @author Jin
 */
public class MemberManagement extends javax.swing.JInternalFrame {

    private Connection conn = MyConnect.getConnection();
    private DefaultTableModel modelMember;

    /**
     * Creates new form JFrameApartment
     */
    /**
     * Creates new form MemeberManagerment
     */
    public MemberManagement() {

        initComponents();
        modelMember = (DefaultTableModel) tbMember.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        headerMember = new javax.swing.JLabel();
        txtMemberName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMember = new javax.swing.JTable();
        lbMemberPhone = new javax.swing.JLabel();
        txtMemberPhone = new javax.swing.JTextField();
        searchPanelMember = new javax.swing.JPanel();
        txtSearchMember = new javax.swing.JTextField();
        lbMemberID = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        txtMemberID = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lbMemberName = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("การจัดการสมาชิก");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        headerMember.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        headerMember.setText("การจัดการสมาชิก");

        txtMemberName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "รหัสสมาชิก", "ชื่อสมาชิก", "เบอร์โทรศัพท์"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMember);

        lbMemberPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMemberPhone.setLabelFor(txtMemberPhone);
        lbMemberPhone.setText("เบอร์โทรศัพท์ :");

        txtMemberPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        searchPanelMember.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtSearchMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchMemberKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout searchPanelMemberLayout = new javax.swing.GroupLayout(searchPanelMember);
        searchPanelMember.setLayout(searchPanelMemberLayout);
        searchPanelMemberLayout.setHorizontalGroup(
            searchPanelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchMember, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanelMemberLayout.setVerticalGroup(
            searchPanelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        lbMemberID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMemberID.setLabelFor(txtMemberID);
        lbMemberID.setText("รหัสสมาชิก :");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        txtMemberID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lbMemberName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMemberName.setLabelFor(txtMemberName);
        lbMemberName.setText("ชื่อสมาชิก :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbMemberPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMemberName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMemberID)
                                    .addComponent(txtMemberName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMemberPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnInsert)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(141, 141, 141)))
                        .addComponent(searchPanelMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerMember)
                        .addGap(292, 292, 292))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(searchPanelMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMemberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMemberID)
                                .addGap(18, 18, 18)
                                .addComponent(lbMemberName)
                                .addGap(18, 18, 18)
                                .addComponent(lbMemberPhone)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(41, 41, 41)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMemberMouseClicked
        // TODO add your handling code here:
        int index = tbMember.getSelectedRow();
        txtMemberID.setText(tbMember.getValueAt(index, 0).toString());
        txtMemberName.setText(tbMember.getValueAt(index, 1).toString());
        txtMemberPhone.setText(tbMember.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tbMemberMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tb_member (mem_id,mem_name,mem_phone) VALUES (?,?,?)";
            PreparedStatement pre = conn.prepareStatement(sql);
            pre.setString(1, txtMemberID.getText());
            pre.setString(2, txtMemberName.getText());
            pre.setString(3, txtMemberPhone.getText());
            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(this, "บันทึกรายการแล้ว", "ผลการบันทึกรายการ", JOptionPane.INFORMATION_MESSAGE);
                txtMemberID.setText("");
                txtMemberName.setText("");
                txtMemberPhone.setText("");
                showData();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tbMember.getSelectedRow();
        if (index != -1) {

            String pk = txtMemberID.getText().trim();
            String sql = "Delete from tb_member where mem_id =?";

            try {
                PreparedStatement pre = conn.prepareStatement(sql);
                pre.setString(1, pk);
                if (pre.executeUpdate() != -1) {
                    JOptionPane.showMessageDialog(this, "ลบรายการแล้ว", "ผลการลบรายการ",
                            JOptionPane.INFORMATION_MESSAGE);
                    txtMemberID.setText("");
                    txtMemberName.setText("");
                    txtMemberPhone.setText("");
                    showData();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int index = tbMember.getSelectedRow();
        if (index != -1) {
            String pk = txtMemberID.getText().trim();
            String sql = "UPDATE tb_member SET "
                    + "mem_name = ?, "
                    + "mem_phone = ? "
                    + "WHERE mem_id = ?";

            try {
                PreparedStatement pre = conn.prepareStatement(sql);
                pre.setString(1, txtMemberName.getText());
                pre.setString(2, txtMemberPhone.getText());
                pre.setString(3, pk);
                if (pre.executeUpdate() != -1) {
                }
                JOptionPane.showMessageDialog(this, "แก้ไขรายการแล้ว", "ผลการบันทึกรายการ",
                        JOptionPane.INFORMATION_MESSAGE);
                txtMemberID.setText("");
                txtMemberName.setText("");
                txtMemberPhone.setText("");
                showData();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMemberKeyReleased
        // TODO add your handling code here:
        String searchText = txtSearchMember.getText();
        try {
            showData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchMemberKeyReleased

    public void showData() {
        try {
//clear data
            int totalRow = tbMember.getRowCount() - 1;
            while (totalRow > - 1) {
                modelMember.removeRow(totalRow);
                totalRow--;
            }
// add record
            String search = txtSearchMember.getText();
            String sql = " SELECT * FROM tb_member "
                    + " where "
                    + " mem_id LIKE ('%" + search + "%' )"
                    + " OR mem_name LIKE ('%" + search + "%')"
                    + " OR mem_phone LIKE ('%" + search + "%')";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            int row = 0;
            while (rs.next()) {
                modelMember.addRow(new Object[0]);
                modelMember.setValueAt(rs.getString("mem_id"), row, 0);
                modelMember.setValueAt(rs.getString("mem_name"), row, 1);
                modelMember.setValueAt(rs.getString("mem_phone"), row, 2);
                row++;
            }
            tbMember.setModel(modelMember);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel headerMember;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMemberID;
    private javax.swing.JLabel lbMemberName;
    private javax.swing.JLabel lbMemberPhone;
    private javax.swing.JPanel searchPanelMember;
    private javax.swing.JTable tbMember;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtMemberPhone;
    private javax.swing.JTextField txtSearchMember;
    // End of variables declaration//GEN-END:variables
}
