/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formManagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stourestaurant.MyConnect;

/**
 *
 * @author Jin
 */
public class StaffManagement extends javax.swing.JInternalFrame {

    private Connection conn = MyConnect.getConnection();
    private DefaultTableModel modelStaff;

    /**
     * Creates new form StaffManagement
     */
    public StaffManagement() {
        initComponents();
        modelStaff = (DefaultTableModel) tbStaff.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanelStaff = new javax.swing.JPanel();
        txtSearchStaff = new javax.swing.JTextField();
        lbStaffID = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtStaffID = new javax.swing.JTextField();
        headerStaff = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtStaffName = new javax.swing.JTextField();
        lbStaffName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();
        lbStaffPhone = new javax.swing.JLabel();
        txtStaffPhone = new javax.swing.JTextField();
        lbStaffPos = new javax.swing.JLabel();
        txtStaffPos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("การจัดการพนักงาน");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        searchPanelStaff.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtSearchStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchStaffKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout searchPanelStaffLayout = new javax.swing.GroupLayout(searchPanelStaff);
        searchPanelStaff.setLayout(searchPanelStaffLayout);
        searchPanelStaffLayout.setHorizontalGroup(
            searchPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanelStaffLayout.setVerticalGroup(
            searchPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        lbStaffID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStaffID.setLabelFor(txtStaffID);
        lbStaffID.setText("รหัสพนักงาน :");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtStaffID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        headerStaff.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        headerStaff.setText("การจัดการพนักงาน");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtStaffName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbStaffName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStaffName.setLabelFor(txtStaffName);
        lbStaffName.setText("ชื่อพนักงาน :");

        tbStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "รหัสพนักงาน", "ชื่อพนักงาน", "เบอร์โทรศัพท์", "ตำแหน่ง"
            }
        ));
        tbStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStaff);

        lbStaffPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStaffPhone.setLabelFor(txtStaffPhone);
        lbStaffPhone.setText("เบอร์โทรศัพท์ :");

        txtStaffPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbStaffPos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStaffPos.setLabelFor(txtStaffPos);
        lbStaffPos.setText("ตำแหน่ง :");

        txtStaffPos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(237, Short.MAX_VALUE)
                        .addComponent(btnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbStaffPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStaffName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStaffPos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStaffID)
                            .addComponent(txtStaffName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffPos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(searchPanelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerStaff)
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(searchPanelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerStaff)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbStaffID)
                            .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbStaffName)
                                .addGap(19, 19, 19))
                            .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStaffPhone)
                            .addComponent(txtStaffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStaffPos)
                            .addComponent(txtStaffPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(36, 36, 36)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchStaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchStaffKeyReleased
        // TODO add your handling code here:
        String searchText = txtSearchStaff.getText();
        try {
            showData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchStaffKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStaffMouseClicked
        // TODO add your handling code here:
        int index = tbStaff.getSelectedRow();
        txtStaffID.setText(tbStaff.getValueAt(index, 0).toString());
        txtStaffName.setText(tbStaff.getValueAt(index, 1).toString());
        txtStaffPhone.setText(tbStaff.getValueAt(index, 2).toString());
        txtStaffPos.setText(tbStaff.getValueAt(index, 3).toString());
    }//GEN-LAST:event_tbStaffMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tb_staff (staff_id,staff_name,staff_phone,staff_pos) VALUES (?,?,?,?)";
            PreparedStatement pre = conn.prepareStatement(sql);
            pre.setString(1, txtStaffID.getText());
            pre.setString(2, txtStaffName.getText());
            pre.setString(3, txtStaffPhone.getText());
            pre.setString(4, txtStaffPos.getText());
            if (pre.executeUpdate() != -1) {
                JOptionPane.showMessageDialog(this, "บันทึกรายการแล้ว", "ผลการบันทึกรายการ", JOptionPane.INFORMATION_MESSAGE);
                txtStaffID.setText("");
                txtStaffName.setText("");
                txtStaffPhone.setText("");
                txtStaffPos.setText("");
                showData();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int index = tbStaff.getSelectedRow();
        if (index != -1) {
            String pk = txtStaffID.getText().trim();
            String sql = "UPDATE tb_staff SET "
                    + "staff_name = ?, "
                    + "staff_phone = ?, "
                    + "staff_pos = ? "
                    + "WHERE staff_id = ?";

            try {
                PreparedStatement pre = conn.prepareStatement(sql);
                pre.setString(1, txtStaffName.getText());
                pre.setString(2, txtStaffPhone.getText());
                pre.setString(3, txtStaffPos.getText());
                pre.setString(4, pk);
                if (pre.executeUpdate() != -1) {
                }
                JOptionPane.showMessageDialog(this, "แก้ไขรายการแล้ว", "ผลการบันทึกรายการ",
                        JOptionPane.INFORMATION_MESSAGE);
                txtStaffID.setText("");
                txtStaffName.setText("");
                txtStaffPhone.setText("");
                txtStaffPos.setText("");
                showData();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tbStaff.getSelectedRow();
        if (index != -1) {

            String pk = txtStaffID.getText().trim();
            String sql = "Delete from tb_staff where staff_id =?";

            try {
                PreparedStatement pre = conn.prepareStatement(sql);
                pre.setString(1, pk);
                if (pre.executeUpdate() != -1) {
                    JOptionPane.showMessageDialog(this, "ลบรายการแล้ว", "ผลการลบรายการ",
                            JOptionPane.INFORMATION_MESSAGE);
                    txtStaffID.setText("");
                    txtStaffName.setText("");
                    txtStaffPhone.setText("");
                    txtStaffPos.setText("");
                    showData();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void showData() {
        try {
//clear data
            int totalRow = tbStaff.getRowCount() - 1;
            while (totalRow > - 1) {
                modelStaff.removeRow(totalRow);
                totalRow--;
            }
// add record
            String search = txtSearchStaff.getText();
            String sql = " SELECT * FROM tb_staff "
                    + " where "
                    + " staff_id LIKE ('%" + search + "%' )"
                    + " OR staff_name LIKE ('%" + search + "%')"
                    + " OR staff_phone LIKE ('%" + search + "%')"
                    + " OR staff_pos LIKE ('%" + search + "%')";
            ResultSet rs = conn.createStatement().executeQuery(sql);
            int row = 0;
            while (rs.next()) {
                modelStaff.addRow(new Object[0]);
                modelStaff.setValueAt(rs.getString("staff_id"), row, 0);
                modelStaff.setValueAt(rs.getString("staff_name"), row, 1);
                modelStaff.setValueAt(rs.getString("staff_phone"), row, 2);
                modelStaff.setValueAt(rs.getString("staff_pos"), row, 3);
                row++;
            }
            tbStaff.setModel(modelStaff);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel headerStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbStaffID;
    private javax.swing.JLabel lbStaffName;
    private javax.swing.JLabel lbStaffPhone;
    private javax.swing.JLabel lbStaffPos;
    private javax.swing.JPanel searchPanelStaff;
    private javax.swing.JTable tbStaff;
    private javax.swing.JTextField txtSearchStaff;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStaffName;
    private javax.swing.JTextField txtStaffPhone;
    private javax.swing.JTextField txtStaffPos;
    // End of variables declaration//GEN-END:variables
}
