/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stourestaurant;

import formManagement.BillManagement;
import formManagement.FoodManagement;
import formManagement.MemberManagement;
import formManagement.StaffManagement;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jin
 */
public class JFrameRest extends javax.swing.JFrame {

    public static Font f2 = new Font("Tahoma", Font.PLAIN, 14);
    private Connection conn = MyConnect.getConnection();

    /**
     * Creates new form JFrameRest
     */
    public JFrameRest() {
        UIManager.put("MenuBar.font", f2);
        UIManager.put("InternalFrame.titleFont", f2);
        UIManager.put("Label.font", f2);
        UIManager.put("Button.font", f2);
        UIManager.put("OptionPane.font", f2);
        UIManager.put("TextField.font", f2);
        UIManager.put("TextArea.font", f2);
        UIManager.put("TextPane.font", f2);
        UIManager.put("InternalFrame.optionDialogTitleFont", f2);
        UIManager.put("OptionPane.messageFont", f2);
        UIManager.put("OptionPane.buttonFont", f2);
        UIManager.put("Table.font", f2);
        UIManager.put("TableHeader.font", f2);
        UIManager.put("ComboBox.font", f2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuManagement = new javax.swing.JMenu();
        menuFood = new javax.swing.JMenuItem();
        menuMember = new javax.swing.JMenuItem();
        menuStaff = new javax.swing.JMenuItem();
        menuBill = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout myDesktopLayout = new javax.swing.GroupLayout(myDesktop);
        myDesktop.setLayout(myDesktopLayout);
        myDesktopLayout.setHorizontalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        myDesktopLayout.setVerticalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        menuManagement.setText("Management");

        menuFood.setText("Food");
        menuFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFoodActionPerformed(evt);
            }
        });
        menuManagement.add(menuFood);

        menuMember.setText("Member");
        menuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMemberActionPerformed(evt);
            }
        });
        menuManagement.add(menuMember);

        menuStaff.setText("Staff");
        menuStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStaffActionPerformed(evt);
            }
        });
        menuManagement.add(menuStaff);

        menuBill.setText("Bill");
        menuBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBillActionPerformed(evt);
            }
        });
        menuManagement.add(menuBill);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuManagement.add(menuExit);

        jMenuBar1.add(menuManagement);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMemberActionPerformed
        // TODO add your handling code here:
        MemberManagement memberPage = new MemberManagement();
        memberPage.setVisible(true);
        myDesktop.add(memberPage);
        memberPage.toFront();
    }//GEN-LAST:event_menuMemberActionPerformed

    private void menuStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStaffActionPerformed
        // TODO add your handling code here:
        StaffManagement staffPage = new StaffManagement();
        staffPage.setVisible(true);
        myDesktop.add(staffPage);
        staffPage.toFront();
    }//GEN-LAST:event_menuStaffActionPerformed

    private void menuBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBillActionPerformed
        // TODO add your handling code here:
        BillManagement billPage = new BillManagement();
        billPage.setVisible(true);
        myDesktop.add(billPage);
        billPage.toFront();
    }//GEN-LAST:event_menuBillActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(this, "ยืนยันการปิดโปรแกรม", "ยืนยัน",
                JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFoodActionPerformed
        // TODO add your handling code here:
        FoodManagement foodPage = new FoodManagement();
        foodPage.setVisible(true);
        myDesktop.add(foodPage);
        foodPage.toFront();
    }//GEN-LAST:event_menuFoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBill;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuFood;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenuItem menuMember;
    private javax.swing.JMenuItem menuStaff;
    private javax.swing.JDesktopPane myDesktop;
    // End of variables declaration//GEN-END:variables
}
